# Generated by Django 6.1.1 on 2026-09-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EN_ATTENTE', 'En attente'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20, verbose_name='profile status'),
        ),
    ]
