# Generated by Django 6.1.1 on 2026-09-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('REGISTRATION', 'Registration'), ('LOGIN', 'Login'), ('DEPOSIT_CREATED', 'Deposit Created'), ('DEPOSIT_APPROVED', 'Deposit Approved'), ('WITHDRAWAL_CREATED', 'Withdrawal Created'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('AI_VIEWED', 'AI Viewed'), ('AI_RENTED', 'AI Rented'), ('REFERRAL_CREATED', 'Referral Created')], max_length=30, verbose_name='event type')),
                ('session_id', models.CharField(blank=True, default='', max_length=100, verbose_name='session ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'analytics event',
                'verbose_name_plural': 'analytics events',
                'ordering': ['-created_at'],
            },
        ),
    ]
