# Generated by Django 6.1.1 on 2026-09-03 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_level', models.IntegerField(verbose_name='referral level')),
                ('source_transaction_type', models.CharField(max_length=50, verbose_name='source transaction type')),
                ('source_transaction_id', models.PositiveIntegerField(verbose_name='source transaction ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='percentage')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('available', 'Available'), ('cancelled', 'Cancelled'), ('revoked', 'Revoked')], default='pending', max_length=20, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='wallet.ledgerentry', verbose_name='ledger entry')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generated', to=settings.AUTH_USER_MODEL, verbose_name='source user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_earned', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'commission',
                'verbose_name_plural': 'commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_level', models.IntegerField(verbose_name='referral level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('parent_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_referrals', to='referrals.referral', verbose_name='parent referral')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_info', to=settings.AUTH_USER_MODEL, verbose_name='referred user')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='referrer')),
            ],
            options={
                'verbose_name': 'referral',
                'verbose_name_plural': 'referrals',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('referrer', 'referred_user'), name='unique_referrer_referred_user')],
            },
        ),
    ]
