# Generated by Django 6.1.1 on 2026-09-05 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
        ('transactions', '0005_deposit_productive_amount_and_more'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_level', models.PositiveIntegerField(verbose_name='referral level')),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='The deposit amount used as the basis for this commission calculation.', max_digits=12, verbose_name='base amount')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='The referral rate percentage applied.', max_digits=5, verbose_name='percentage')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The actual commission amount allocated (base_amount * percentage / 100).', max_digits=12, verbose_name='commission amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=20, verbose_name='status')),
                ('reference', models.CharField(help_text='Unique reference: DEP-{deposit_id}-LVL-{level}', max_length=100, unique=True, verbose_name='reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_allocations_received', to=settings.AUTH_USER_MODEL, verbose_name='beneficiary (referrer)')),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='referrals.commission', verbose_name='commission')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_allocations', to='transactions.deposit', verbose_name='deposit')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_allocations', to='wallet.ledgerentry', verbose_name='ledger entry')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_allocations_generated', to=settings.AUTH_USER_MODEL, verbose_name='source user (depositor)')),
            ],
            options={
                'verbose_name': 'referral allocation',
                'verbose_name_plural': 'referral allocations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['beneficiary', 'status'], name='alloc_beneficiary_status_idx'), models.Index(fields=['deposit', 'status'], name='alloc_deposit_status_idx'), models.Index(fields=['reference'], name='alloc_reference_idx')],
                'constraints': [models.UniqueConstraint(fields=('deposit', 'referral_level'), name='unique_allocation_per_deposit_level')],
            },
        ),
    ]
