# Generated by Django 6.1.1 on 2026-09-22 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referralallocation'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['user', 'status'], name='commission_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['source_user'], name='commission_source_user_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status'], name='commission_status_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['created_at'], name='commission_created_idx'),
        ),
    ]
