# Generated by Django 6.1.1 on 2026-09-22 11:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0005_airevenue_revenue_user_status_idx_and_more'),
        ('referrals', '0003_commission_commission_user_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='source_transaction_id',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='source_transaction_type',
        ),
        migrations.AddField(
            model_name='commission',
            name='ai_revenue',
            field=models.ForeignKey(blank=True, help_text='The revenue event that generated this commission.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='ai_services.airevenue', verbose_name='AI revenue source'),
        ),
        migrations.AddField(
            model_name='commission',
            name='gross_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The machine revenue before commissions.', max_digits=12, verbose_name='gross revenue'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='commission amount'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='percentage'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='source_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generated', to=settings.AUTH_USER_MODEL, verbose_name='source user (referred)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_earned', to=settings.AUTH_USER_MODEL, verbose_name='user (referrer)'),
        ),
    ]
