# Generated by Django 6.1.1 on 2026-09-03 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('AI', 'AI'), ('REFERRAL', 'Referral'), ('ACCOUNT', 'Account'), ('TECHNICAL', 'Technical'), ('OTHER', 'Other')], max_length=20, verbose_name='category')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10, verbose_name='priority')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING_USER', 'Waiting for User'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='status')),
                ('last_reply_at', models.DateTimeField(blank=True, null=True, verbose_name='last reply at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'support ticket',
                'verbose_name_plural': 'support tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('attachment', models.FileField(blank=True, default='', upload_to='support_attachments/', verbose_name='attachment')),
                ('is_internal_note', models.BooleanField(default=False, verbose_name='is internal note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'support message',
                'verbose_name_plural': 'support messages',
                'ordering': ['created_at'],
            },
        ),
    ]
