# Generated by Django 6.1.1 on 2026-09-03 16:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200, unique=True, verbose_name='event id')),
                ('provider', models.CharField(max_length=100, verbose_name='provider')),
                ('event_type', models.CharField(max_length=100, verbose_name='event type')),
                ('payload', models.JSONField(verbose_name='payload')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'payment event',
                'verbose_name_plural': 'payment events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('instructions', models.TextField(blank=True, help_text='Payment instructions shown to users.', verbose_name='instructions')),
                ('requires_proof', models.BooleanField(default=True, verbose_name='requires proof')),
                ('requires_transaction_id', models.BooleanField(default=True, verbose_name='requires transaction id')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='minimum amount')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='maximum amount')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='fee percentage')),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='fixed fee')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('display_order', models.IntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='fee')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='net amount')),
                ('withdrawal_number', models.CharField(max_length=200, verbose_name='withdrawal number')),
                ('withdrawal_account_name', models.CharField(blank=True, max_length=200, verbose_name='withdrawal account name')),
                ('external_reference', models.CharField(blank=True, max_length=200, verbose_name='external reference')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('withdrawal_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='transactions.paymentmethod', verbose_name='withdrawal method')),
            ],
            options={
                'verbose_name': 'withdrawal',
                'verbose_name_plural': 'withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='transaction id')),
                ('proof', models.ImageField(blank=True, upload_to='deposit_proofs/', verbose_name='proof')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending_review', max_length=20, verbose_name='status')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deposits', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='transactions.paymentmethod', verbose_name='payment method')),
            ],
            options={
                'verbose_name': 'deposit',
                'verbose_name_plural': 'deposits',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'transaction_id')},
            },
        ),
    ]
