# Generated by Django 6.1.1 on 2026-09-03 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deposit',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rejected'), _negated=True), fields=('user', 'transaction_id'), name='unique_user_transaction_id_non_rejected'),
        ),
    ]
