# Generated by Django 6.1.1 on 2026-09-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_deposit_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Phone number used to make the Mobile Money transaction.', max_length=20, verbose_name='transaction phone number'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='reception_number',
            field=models.CharField(blank=True, default='', help_text='Mobile Money number used to receive the deposit.', max_length=20, verbose_name='reception number'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='ussd_code',
            field=models.CharField(blank=True, default='', help_text='Generated USSD code used for this deposit.', max_length=200, verbose_name='USSD code'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Mobile Money phone number used to receive deposits (e.g. 690123456).', max_length=20, verbose_name='reception phone number'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='ussd_template',
            field=models.CharField(blank=True, default='', help_text='USSD code template with {amount} placeholder. E.g. *126*14*5555*{amount}#', max_length=200, verbose_name='USSD template'),
        ),
    ]
