# Generated by Django 6.1.1 on 2026-09-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_deposit_phone_number_deposit_reception_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='reception_name',
            field=models.CharField(blank=True, default='', help_text='Name displayed to users when receiving payment (e.g. John Mobile Money).', max_length=150, verbose_name='reception name'),
        ),
    ]
