# Generated by Django 6.1.1 on 2026-09-05 16:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_paymentmethod_reception_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='productive_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount available for AI revenue calculations after referral commissions.', max_digits=12, verbose_name='productive amount'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='referral_commission_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total referral commissions deducted from this deposit.', max_digits=12, verbose_name='referral commission total'),
        ),
    ]
