# Generated by Django 6.1.1 on 2026-09-22 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_deposit_productive_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['status'], name='deposit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['user', 'status'], name='deposit_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['created_at'], name='deposit_created_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['user', 'created_at'], name='deposit_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status'], name='withdrawal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'status'], name='withdrawal_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['created_at'], name='withdrawal_created_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'created_at'], name='withdrawal_user_created_idx'),
        ),
    ]
