# Generated by Django 6.1.1 on 2026-09-22 11:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_deposit_deposit_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='productive_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Deprecated: 100% of deposit now goes to machine. Use deposit.amount directly.', max_digits=12, verbose_name='productive amount'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='referral_commission_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Deprecated: commissions are now taken from machine revenue, not deposits.', max_digits=12, verbose_name='referral commission total'),
        ),
    ]
