# Generated by Django 6.1.1 on 2026-10-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_deposit_productive_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Unique payment reference sent to Tara Money (productId).', max_length=100, unique=True, verbose_name='reference')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure'), ('expired', 'Expired')], default='pending', max_length=12, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in XAF locked for this attempt.', max_digits=12, verbose_name='amount')),
                ('payment_id', models.CharField(blank=True, default='', help_text='Provider payment identifier received in the webhook.', max_length=200, verbose_name='payment id')),
                ('pay_url', models.CharField(blank=True, default='', help_text='generalLink returned by Tara Money.', max_length=500, verbose_name='payment url')),
                ('links', models.JSONField(blank=True, default=dict, help_text='All payment links returned by the provider.', verbose_name='links')),
                ('provider_payload', models.JSONField(blank=True, default=dict, help_text='Last verified payload received from the provider.', verbose_name='provider payload')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=300, verbose_name='failure reason')),
                ('conflict', models.BooleanField(default=False, help_text='Payment confirmed by the provider but the deposit could not be credited automatically (manual reconciliation required).', verbose_name='conflict')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='last checked at')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='transactions.deposit', verbose_name='deposit')),
            ],
            options={
                'verbose_name': 'deposit attempt',
                'verbose_name_plural': 'deposit attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='attempt_status_created_idx'), models.Index(fields=['deposit', 'status'], name='attempt_deposit_status_idx'), models.Index(fields=['expires_at'], name='attempt_expires_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('deposit',), name='unique_success_attempt_per_deposit')],
            },
        ),
    ]
