# Generated by Django 6.1.1 on 2026-10-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_seed_tara_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositattempt',
            name='channel',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('wave', 'Wave'), ('card', 'Payment link')], default='card', help_text='Payment channel chosen by the user: direct debit on the phone number or payment link.', max_length=12, verbose_name='channel'),
        ),
        migrations.AddField(
            model_name='depositattempt',
            name='launched_at',
            field=models.DateTimeField(blank=True, help_text='Moment ou le debit direct a ete demande au prestataire.', null=True, verbose_name='launched at'),
        ),
        migrations.AddField(
            model_name='depositattempt',
            name='network',
            field=models.CharField(blank=True, default='', help_text="Tara Money network parameter (empty or 'wave').", max_length=20, verbose_name='network'),
        ),
        migrations.AddField(
            model_name='depositattempt',
            name='vendor',
            field=models.CharField(blank=True, default='', help_text='Operator identified by Tara Money (ex: ORANGE_CAMEROON).', max_length=50, verbose_name='vendor'),
        ),
    ]
