# Generated by Django 6.1.1 on 2026-09-03 16:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='available balance')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='pending balance')),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total deposited')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total withdrawn')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total earnings')),
                ('referral_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='referral earnings')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('ai_purchase', 'AI Purchase'), ('ai_revenue', 'AI Revenue'), ('referral_commission', 'Referral Commission'), ('bonus', 'Bonus'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=30, verbose_name='entry type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='balance before')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='balance after')),
                ('reference_type', models.CharField(blank=True, max_length=100, verbose_name='reference type')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='reference id')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallet.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'ledger entry',
                'verbose_name_plural': 'ledger entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='ledger_entry_user_idx'), models.Index(fields=['wallet'], name='ledger_entry_wallet_idx'), models.Index(fields=['entry_type'], name='ledger_entry_type_idx'), models.Index(fields=['created_at'], name='ledger_entry_created_idx')],
            },
        ),
    ]
