# Generated by Django 6.1.1 on 2026-09-03 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('display_order', models.IntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'AI category',
                'verbose_name_plural': 'AI categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'AI model',
                'verbose_name_plural': 'AI models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AiOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, default='', upload_to='ai_images/', verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('duration_days', models.IntegerField(verbose_name='duration (days)')),
                ('revenue_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='revenue frequency')),
                ('revenue_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage'), ('variable', 'Variable')], max_length=20, verbose_name='revenue type')),
                ('revenue_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='revenue value')),
                ('revenue_metric', models.CharField(blank=True, default='', max_length=100, verbose_name='revenue metric')),
                ('conditions', models.TextField(blank=True, default='', verbose_name='conditions')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('total_rentals', models.IntegerField(default=0, verbose_name='total rentals')),
                ('display_order', models.IntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='ai_services.aimodel', verbose_name='AI model')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='ai_services.aicategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'AI offer',
                'verbose_name_plural': 'AI offers',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AiRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount paid')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='status')),
                ('total_revenue_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total revenue earned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='ai_services.aioffer', verbose_name='offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_rentals', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI rental',
                'verbose_name_plural': 'AI rentals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('credited_at', models.DateTimeField(blank=True, null=True, verbose_name='credited at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_revenues', to='wallet.ledgerentry', verbose_name='ledger entry')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='ai_services.aioffer', verbose_name='offer')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='ai_services.airental', verbose_name='rental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_revenues', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI revenue',
                'verbose_name_plural': 'AI revenues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='airental',
            constraint=models.UniqueConstraint(fields=('user', 'offer', 'start_date'), name='unique_user_offer_start'),
        ),
    ]
