# Generated by Django 6.1.1 on 2026-09-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='ai_models/', verbose_name='image'),
        ),
    ]
