# Generated by Django 6.1.1 on 2026-09-05 16:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0003_add_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='airental',
            name='productive_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The capital base used for revenue calculations, after referral commissions.', max_digits=12, verbose_name='productive amount'),
        ),
        migrations.AlterField(
            model_name='airevenue',
            name='payment_reference',
            field=models.CharField(max_length=255, unique=True, verbose_name='payment reference'),
        ),
    ]
