# Generated by Django 6.1.1 on 2026-09-22 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0004_airental_productive_amount_and_more'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='airevenue',
            index=models.Index(fields=['user', 'status'], name='revenue_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='airevenue',
            index=models.Index(fields=['user', 'created_at'], name='revenue_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='airevenue',
            index=models.Index(fields=['status'], name='revenue_status_idx'),
        ),
    ]
