# Generated by Django 6.1.1 on 2026-09-03 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('message_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('BROADCAST', 'Broadcast'), ('AI_USERS', 'AI Users'), ('REFERRALS', 'Referrals')], default='INDIVIDUAL', max_length=20, verbose_name='message type')),
                ('group_filter', models.CharField(blank=True, default='', max_length=100, verbose_name='group filter')),
                ('is_system_message', models.BooleanField(default=False, verbose_name='is system message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DEPOSIT_SUBMITTED', 'Deposit Submitted'), ('DEPOSIT_APPROVED', 'Deposit Approved'), ('DEPOSIT_REJECTED', 'Deposit Rejected'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('AI_ACTIVATED', 'AI Activated'), ('AI_EXPIRED', 'AI Expired'), ('COMMISSION_RECEIVED', 'Commission Received'), ('NEW_REFERRAL', 'New Referral'), ('SECURITY_ALERT', 'Security Alert'), ('SYSTEM_MESSAGE', 'System Message')], max_length=30, verbose_name='notification type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='link')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
